import { CONFIG } from '../utils/config';

export const ENDPOINTS = {
  ACCOUNTS: `${CONFIG.ACCOUNTS_API}`,
  LOCATIONS: `${CONFIG.LOCATIONS_API}`,
  USERS: `${CONFIG.USERS_API}`,
  GROUPS: `${CONFIG.GROUPS_API}`,
  ACTIVITIES: `${CONFIG.ACTIVITIES_API}`,
  INVENTORY: `${CONFIG.INVENTORY}`,
  ORDERS: `${CONFIG.ORDERS_API}`,
  JOBS: `${CONFIG.JOBS_API}`,
  ONBOARDING: `${CONFIG.ONBOARDING_API}`,
  OTP: `${CONFIG.OTP_API}`,
  INTEGRATION: `${CONFIG.INTEGRATIONS_API}`,
};
