export const QUERY = {
  ACTIVITY_LIST: 'activity_list',
  INVENTORY_LIST: 'inventory_list',
  INVENTORY_DETAILS: 'inventory_details',
  ORDER_LIST: 'order_list',
  ORDER_DETAILS: 'order_details',
  GROUP_LIST: 'group_list',
  GROUP_DETAILS: 'group_details',
  JOB_LIST: 'job_list',
  JOB_DETAILS: 'job_details',
  LOCATION_LIST: 'location_list',
  LOCATION_DETAILS: 'location_details',
  USER_LIST: 'user_list',
  USER_DETAILS: 'user_details',
  USER_EXISTS: 'user_exists',
  WAREHOUSE_LIST: 'warehouse_list',
  WAREHOUSE_DETAILS: 'warehouse_details',
  INTEGRATION_DATA_LIST: 'integration_data_list',
  EXCHANGE_CODE_FOR_TOKEN: 'exchange_code_for_token',
  INTEGRATION_DATA_DETAILS: 'integration_data_details',
};
