export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password/:step?',
  FORGOT_PASSWORD_ROOT: '/forgot-password',
  FORGOT_PASSWORD_CODE: '/forgot-password/code_verification',
  FORGOT_PASSWORD_NEW: '/forgot-password/new_password',
  FORGOT_PASSWORD_SUCCESS: '/forgot-password/success',
  SIGNUP: '/signup/:step?',
  ACTIVATE: '/activate/:step?',
  SIGNUP_ROOT: '/signup',
  SIGNUP_COMPANY: '/signup/company',
  SIGNUP_OTP_VERIFICATION: '/signup/otp_verification',
  DASHBOARD: '/dashboard',
  INVENTORY: '/inventory/:tab/:breadcrumbs?',
  JOBS: '/jobs/:breadcrumbs?',
  ORDERS: '/orders/:breadcrumbs?',
  ADMINWIZARD: '/admin/wizard',
  USERWIZARD: '/wizard',
  SHIPMENTS: '/shipments',
  WORKFLOWS: '/workflows',
  LOCATIONS: '/locations/:tab/:breadcrumbs?',
  PROFILE: '/profile/:tab/:breadcrumbs?',
  ADMINISTRATION: '/admin/:tab?/:breadcrumbs?',
  ACTIVITY: '/activity',
};
